repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: tag-runtime

  # A short description of the repository that will show up on GitHub
  description: 🏃🏿‍♀️🏃🏽‍♀️🏃🏻‍♂️🕒CNCF Technical Advisory Group for Runtime

  # A URL with more information about the repository
  homepage: https://cncf.io/projects

